services:
  phpfpm:
    extends:
      file: docker-compose.yml
      service: phpfpm
  db:
    extends:
      file: docker-compose.yml
      service: db
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  # MinIO - AWS S3 Compatible Object Storage per sviluppo locale
  minio:
    image: "minio/minio:latest"
    container_name: "minio_${APP_NAME}"
    ports:
      - "${FORWARD_MINIO_PORT:-9002}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-9003}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - "./docker/volumes/minio/data:/data/minio"
    command: 'minio server /data/minio --console-address ":9001"'
    platform: linux/amd64
    networks:
      - laravel
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      retries: 3
      timeout: 5s

  # MailPit - SMTP testing tool per catturare email in sviluppo
  mailpit:
    container_name: "mailpit_${APP_NAME}"
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge 