version: "3.8"

# Docker Compose per ambiente di sviluppo
# Estende docker-compose.yml aggiungendo servizi di sviluppo come MinIO

services:
  # MinIO - AWS S3 Compatible Object Storage per sviluppo locale
  minio:
    image: minio/minio:latest
    container_name: "minio_${APP_NAME}"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"  # API MinIO
      - "9001:9001"  # Console Web MinIO
    volumes:
      - "./docker/volumes/minio/data:/data"
    command: server /data --console-address ":9001"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MailHog - SMTP testing tool per catturare email in sviluppo
  mailhog:
    image: mailhog/mailhog:latest
    container_name: "mailhog_${APP_NAME}"
    restart: always
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web interface
    networks:
      - laravel

networks:
  laravel:
    external: true 