version: "3.8"

# Docker Compose per ambiente di sviluppo
# Estende docker-compose.yml aggiungendo servizi di sviluppo come MinIO

services:
  # MinIO - AWS S3 Compatible Object Storage per sviluppo locale
  minio:
    image: minio/minio:latest
    container_name: "minio_${APP_NAME}"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9003:9000"  # API MinIO
      - "9004:9001"  # Console Web MinIO
    volumes:
      - "./docker/volumes/minio/data:/data"
    command: server /data --console-address ":9001"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # needed for mails testing
  mailpit:
    container_name: "mailpit_${APP_NAME}"
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"

  # Elasticsearch - Search and analytics engine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: "elasticsearch_${APP_NAME}"
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./docker/volumes/elasticsearch/data:/usr/share/elasticsearch/data"
    networks:
      - laravel

networks:
  laravel: 